/**
 * Automatically generated by the EPF PipelineConverter tool
 * Warning: This file serves as a starting point only, and ensure you check for any missing or incorrect values
 */
library "epf"
boolean isProductionDeployment = env.BRANCH_NAME ==~ /^(release|hotfix).*/
def approvers = 'accounts\\en2807'

env.CNP_CIGNA_GIT='89b25140-4e3e-4b59-b3e5-2954781c574e'

withCredentials([string(credentialsId: 'sonar', variable: 'SONAR_TOKEN')]) {
 List phasesToRun = [
    [
        moduleType              : "maven",
        moduleName              : "cnp-build-publish-maven-create",
        subCommand              : "build",
        branchPattern           : '.*',
        isProductionDeployment  : false,
        args                    : [
            publish     : true,
            pomFile     : "pom.xml",
            buildGoals  : "clean install -B -Dsonar.buildbreaker.skip=true -Dmaven.test.skip=true"
        ]
    ],

    [
        moduleType            : 'quality',
        moduleName            : 'cnp-quality-check-sonarqube',
        subCommand            : 'scan',
        branchPattern         : '^(develop|feature|release).*',
        sdlcEnvironment       : 'dev',
        isProductionDeployment: false,
        args                  : [
            projectName: 'dg-medical-membership-update-processor'
        ]
    ],
    [
        moduleType            : 'quality',
        moduleName            : 'cnp-quality-profile-checkmarx',
        subCommand            : 'scan',
        branchPattern         : '^(develop|feature|release).*',
        sdlcEnvironment       : 'dev',
        isProductionDeployment: false,
        args                  : [
            cxProjectName               : 'dg-medical-membership-update-processor',
            cxPreset                    : '36',
            cxGroupId                   : 'e2640d1b-15fe-4e91-aa45-09f82a082b6a',
            cxVulnerabilityThreshValue  : 'RED'
        ]
    ],
    [
        moduleType            : 'docker',
        branchPattern         : '^(develop|feature|release).*',
        sdlcEnvironment       : 'dev',
        isProductionDeployment: false,
        moduleName            : 'cnp-build-image',
        subCommand            : 'buildimage',
        serviceAccount        : 'kaniko',
        args                  : [
            org                         : 'benefitmanagemententities',
            artifact                    : 'lookup:publishUrl',
            registry                    : 'registry-dev.cigna.com',
            generateDockerFile          : true,
            appendCommitIdToTag         : true,
//            appendBuildNumberToTag      : true,
            buildOnNonDeployableBranch  : true,
            skipBuildIfExists           : true
        ]
    ],
//     [
//         moduleType            : 'pcf',
//         moduleName            : 'cnp-deploy-pcf',
//         subCommand            : 'deploy',
//         branchPattern         : '.*',
//         sdlcEnvironment       : 'dev',
//         isProductionDeployment: false,
//         args                  : [
//             appName                          : 'dg-medical-membership-update-processor-dev-candidate',
//             foundation                       : 'ch3pcf04',
//             organization                     : 'Benefit-MGMT-Entities',
//             space                            : 'development',
//             env                              : 'dev',
//             artifact                         : 'lookup:publishUrl',
//             autoscale                        : false,
//             messagingDestinationsTemp        : '[TP.DG.MEMBERSHIP.PUBLISHER, TP.MEMBERSHIP.LATEST, TP.MEMBERSHIP.EN.LATEST]',
//             messagingDestinations            : '[TP.DG.MEMBERSHIP.PUBLISHER, TP.MEMBERSHIP.LATEST, TP.MEMBERSHIP.EN.LATEST]',
//         ]
//     ],
    [
        moduleType            : 'openshift',
        moduleName            : 'cnp-deploy-argorollouts',
        subCommand            : 'deploy',
        branchPattern         : '^(develop|feature|release).*',
        sdlcEnvironment       : 'dev',
        isProductionDeployment: false,
        args                  : [
            appName                       : 'dg-medical-membership-update-processor-dev',
            namespace                     : 'membershipentity-dev',
            platform                      : 'OpenShift',
            ingressBaseHost               : 'apps-1.hs-1-nonprod.openshift.cignacloud.com',
            imageName                     : 'lookup:imageName',
            imageTag                      : 'lookup:tagName',
            configRepo                    : 'https://github.sys.cigna.com/cigna/membershipentity-dev-argocd',
            useArgoCD                     : 'true',
            argoAppName                   : 'dg-medical-membership-update-processor-dev',
            server                        : 'https://api.hs-1-nonprod.openshift.cignacloud.com:6443',
            argoCDServer                  : 'argocd-devops.apps.hs-1-nonprod.openshift.cignacloud.com',
            cluster                       : 'hs-1-nonprod',
            configDir                     : 'dev',
            env                           : 'dev'
        ]
    ],
//     [
//         parallelType: 'jenkins',
//         sdlcEnvironment: 'DEPLOYDEV',
//         branchPattern  : '.*',
//         phases: [
//             DEPLOYDEV: [
//                 moduleType            : 'test',
//                 moduleName            : 'cnp-jenkins-job-build',
//                 subCommand            : 'build',
//                 branchPattern         : '.*',
//                 sdlcEnvironment       : '',
//                 isProductionDeployment: false,
//                 args                  : [
//                     jobName               : 'orchestrators-folders/job/<insert-folder-name>/job/Testing/job/dev/job/test-pipeline/job/<insert-default-branch>'
//                 ],
//             ]
//         ]
//     ],
//     [
//         moduleType            : 'pcf',
//         moduleName            : 'cnp-deploy-pcf',
//         subCommand            : 'cutover',
//         branchPattern         : '.*',
//         sdlcEnvironment       : 'dev',
//         isProductionDeployment: false,
//         args                  : [
//             appName                          : 'dg-medical-membership-update-processor-dev-candidate',
//             targetAppName                    : 'dg-medical-membership-update-processor-dev',
//             foundation                       : 'ch3pcf04',
//             organization                     : 'Benefit-MGMT-Entities',
//             space                            : 'development',
//             env                              : 'dev'
//         ]
//     ],
    [
        moduleType            : 'openshift',
        moduleName            : 'cnp-deploy-argorollouts',
        subCommand            : 'promote',
        branchPattern         : '^(develop|feature|release).*',
        sdlcEnvironment       : 'dev',
        isProductionDeployment: false,
        args                  : [
            appName                       : 'dg-medical-membership-update-processor-dev',
            namespace                     : 'membershipentity-dev',
            platform                      : 'OpenShift',
            useArgoCD                     : 'true',
            server                        : 'https://api.hs-1-nonprod.openshift.cignacloud.com:6443',
            argoCDServer                  : 'argocd-devops.apps.hs-1-nonprod.openshift.cignacloud.com',
            cluster                       : 'hs-1-nonprod',
            configDir                     : 'dev',
            env                           : 'dev'
        ]
    ],
//     [
//         emailRecipients: '',
//         branchPattern: '.*',
//         lintingTypes: [
//             approvalrequest: [
//                 timeOut: 120,
//                 message: 'Do you want to continue deployment to qa?',
//                 id: 'cnpApprove',
//                 submitter: '',
//             ],
//         ],
//     ],
//     [
//         moduleType            : 'pcf',
//         moduleName            : 'cnp-deploy-pcf',
//         subCommand            : 'deploy',
//         branchPattern         : '.*',
//         sdlcEnvironment       : 'qa',
//         isProductionDeployment: false,
//         args                  : [
//             appName                          : 'dg-medical-membership-update-processor-qa-candidate',
//             foundation                       : 'ch3pcf01',
//             organization                     : 'Benefit-MGMT-Entities',
//             space                            : 'qa',
//             env                              : 'qa',
//             artifact                         : 'lookup:publishUrl',
//             autoscale                        : false,
//             messagingDestinationsTemp : '[TP.DG.MEMBERSHIP.PUBLISHER, TP.MEMBERSHIP.LATEST, TP.MEMBERSHIP.EN.LATEST]',
//             messagingDestinations : '[TP.DG.MEMBERSHIP.PUBLISHER, TP.MEMBERSHIP.LATEST, TP.MEMBERSHIP.EN.LATEST]',
//         ]
//     ],
    [
        moduleType            : 'openshift',
        moduleName            : 'cnp-deploy-argorollouts',
        subCommand            : 'deploy',
        branchPattern         : '^(develop|feature|release).*',
        sdlcEnvironment       : 'qa',
        isProductionDeployment: false,
        args                  : [
            appName                       : 'dg-medical-membership-update-processor-qa',
            namespace                     : 'membershipentity-qa',
            platform                      : 'OpenShift',
            ingressBaseHost               : 'apps-3.hs-3-nonprod.openshift.evernorthcloud.com',
            imageName                     : 'lookup:imageName',
            imageTag                      : 'lookup:tagName',
            configRepo                    : 'https://github.sys.cigna.com/cigna/membershipentity-qa-argocd',
            useArgoCD                     : 'true',
            argoAppName                   : 'dg-medical-membership-update-processor-qa',
            server                        : 'https://api.hs-3-nonprod.openshift.evernorthcloud.com:6443',
            argoCDServer                  : 'argocd-devops.apps.hs-3-nonprod.openshift.evernorthcloud.com',
            cluster                       : 'hs-3-nonprod',
            configDir                     : 'qa',
            env                           : 'qa'
        ]
    ],
//     [
//         parallelType: 'jenkins',
//         sdlcEnvironment: 'DEPLOYQA',
//         branchPattern  : '.*',
//         phases: [
//             DEPLOYQA: [
//                 moduleType            : 'test',
//                 moduleName            : 'cnp-jenkins-job-build',
//                 subCommand            : 'build',
//                 branchPattern         : '.*',
//                 sdlcEnvironment       : '',
//                 isProductionDeployment: false,
//                 args                  : [
//                     jobName               : 'orchestrators-folders/job/<insert-folder-name>/job/Testing/job/qa/job/test-pipeline/job/<insert-default-branch>'
//                 ],
//             ]
//         ]
//     ],
//     [
//         emailRecipients: '',
//         branchPattern: '.*',
//         lintingTypes: [
//             approvalrequest: [
//                 timeOut: 120,
//                 message: 'Route Blue ==> Green in qa?',
//                 id: 'cnpApprove',
//                 submitter: '',
//             ],
//         ],
//     ],
//     [
//         moduleType            : 'pcf',
//         moduleName            : 'cnp-deploy-pcf',
//         subCommand            : 'cutover',
//         branchPattern         : '.*',
//         sdlcEnvironment       : 'qa',
//         isProductionDeployment: false,
//         args                  : [
//             appName                          : 'dg-medical-membership-update-processor-qa-candidate',
//             targetAppName                    : 'dg-medical-membership-update-processor-qa',
//             foundation                       : 'ch3pcf01',
//             organization                     : 'Benefit-MGMT-Entities',
//             space                            : 'qa',
//             env                              : 'qa'
//         ]
//     ],
    [
        moduleType            : 'openshift',
        moduleName            : 'cnp-deploy-argorollouts',
        subCommand            : 'promote',
        branchPattern         : '^(develop|feature|release).*',
        sdlcEnvironment       : 'qa',
        isProductionDeployment: false,
        args                  : [
            appName                       : 'dg-medical-membership-update-processor-qa',
            namespace                     : 'membershipentity-qa',
            platform                      : 'OpenShift',
            useArgoCD                     : 'true',
            server                        : 'https://api.hs-3-nonprod.openshift.evernorthcloud.com:6443',
            argoCDServer                  : 'argocd-devops.apps.hs-3-nonprod.openshift.evernorthcloud.com',
            cluster                       : 'hs-3-nonprod',
            configDir                     : 'qa',
            env                           : 'qa'
        ]
    ],
//     [
//         emailRecipients: '',
//         branchPattern: '.*',
//         lintingTypes: [
//             approvalrequest: [
//                 timeOut: 120,
//                 message: 'Do you want to continue deployment to uat?',
//                 id: 'cnpApprove',
//                 submitter: '',
//             ],
//         ],
//     ],
//     [
//         moduleType            : 'pcf',
//         moduleName            : 'cnp-deploy-pcf',
//         subCommand            : 'deploy',
//         branchPattern         : '.*',
//         sdlcEnvironment       : 'uat',
//         isProductionDeployment: false,
//         args                  : [
//             appName                          : 'dg-medical-membership-update-processor-uat-candidate',
//             foundation                       : 'ch3pcf01',
//             organization                     : 'Benefit-MGMT-Entities',
//             space                            : 'UAT',
//             env                              : 'uat',
//             artifact                         : 'lookup:publishUrl',
//             autoscale                        : false,
//             messagingDestinationsTemp : '[TP.DG.MEMBERSHIP.PUBLISHER, TP.MEMBERSHIP.LATEST, TP.MEMBERSHIP.EN.LATEST]',
//             messagingDestinations : '[TP.DG.MEMBERSHIP.PUBLISHER, TP.MEMBERSHIP.LATEST, TP.MEMBERSHIP.EN.LATEST]',
//         ]
//     ],
    [
        moduleType            : 'openshift',
        moduleName            : 'cnp-deploy-argorollouts',
        subCommand            : 'deploy',
        branchPattern         : '^(develop|feature|release).*',
        sdlcEnvironment       : 'uat',
        isProductionDeployment: false,
        args                  : [
            appName                       : 'dg-medical-membership-update-processor-uat',
            namespace                     : 'membershipentity-uat',
            platform                      : 'OpenShift',
            ingressBaseHost               : 'apps-3.hs-3-nonprod.openshift.evernorthcloud.com',
            imageName                     : 'lookup:imageName',
            imageTag                      : 'lookup:tagName',
            configRepo                    : 'https://github.sys.cigna.com/cigna/membershipentity-uat-argocd',
            useArgoCD                     : 'true',
            argoAppName                   : 'dg-medical-membership-update-processor-uat',
            server                        : 'https://api.hs-3-nonprod.openshift.evernorthcloud.com:6443',
            argoCDServer                  : 'argocd-devops.apps.hs-3-nonprod.openshift.evernorthcloud.com',
            cluster                       : 'hs-3-nonprod',
            configDir                     : 'uat',
            env                           : 'uat'
        ]
    ],
//     [
//         emailRecipients: '',
//         branchPattern: '.*',
//         lintingTypes: [
//             approvalrequest: [
//                 timeOut: 120,
//                 message: 'Route Blue ==> Green in uat?',
//                 id: 'cnpApprove',
//                 submitter: '',
//             ],
//         ],
//     ],
//     [
//         moduleType            : 'pcf',
//         moduleName            : 'cnp-deploy-pcf',
//         subCommand            : 'cutover',
//         branchPattern         : '.*',
//         sdlcEnvironment       : 'uat',
//         isProductionDeployment: false,
//         args                  : [
//             appName                          : 'dg-medical-membership-update-processor-uat-candidate',
//             targetAppName                    : 'dg-medical-membership-update-processor-uat',
//             foundation                       : 'ch3pcf01',
//             organization                     : 'Benefit-MGMT-Entities',
//             space                            : 'UAT',
//             env                              : 'uat'
//         ]
//     ],
    [
        moduleType            : 'openshift',
        moduleName            : 'cnp-deploy-argorollouts',
        subCommand            : 'promote',
        branchPattern         : '^(develop|feature|release).*',
        sdlcEnvironment       : 'uat',
        isProductionDeployment: false,
        args                  : [
            appName                       : 'dg-medical-membership-update-processor-uat',
            namespace                     : 'membershipentity-uat',
            platform                      : 'OpenShift',
            useArgoCD                     : 'true',
            server                        : 'https://api.hs-3-nonprod.openshift.evernorthcloud.com:6443',
            argoCDServer                  : 'argocd-devops.apps.hs-3-nonprod.openshift.evernorthcloud.com',
            cluster                       : 'hs-3-nonprod',
            configDir                     : 'uat',
            env                           : 'uat'
        ]
    ],
    [
        emailRecipients: '',
        branchPattern: '^(release|hotfix).*',
        lintingTypes: [
            approvalrequest: [
                timeOut: 120,
                message: 'Do you want to publish to prod quay?',
                id: 'cnpApprove',
                submitter: approvers,
            ],
        ],
    ],
    [
        moduleType            : 'docker',
        branchPattern         : '^(release|hotfix).*',
        sdlcEnvironment       : 'prod',
        isProductionDeployment: true,
        moduleName            : 'cnp-publish-image',
        subCommand            : 'publishimage',
        serviceAccount        : 'kaniko',
        args                  : [
            sourceImage                     : 'lookup:{cnp-build-image:publishUrl}',
            signImage                       : true,
            repository                      : 'registry.cigna.com'
        ]
    ],
//     [
//         emailRecipients: '',
//         branchPattern: 'develop',
//         lintingTypes: [
//             approvalrequest: [
//                 timeOut: 120,
//                 message: 'Do you want to create a release branch and pipeline?',
//                 id: 'cnpApprove',
//                 submitter: '',
//             ],
//         ],
//     ],
    [
        emailRecipients: '',
        branchPattern: '^(release|hotfix).*',
        lintingTypes: [
            approvalrequest: [
                timeOut: 120,
                message: 'Do you want to continue deployment to prod candidate?',
                id: 'cnpApprove',
                submitter: approvers,
            ],
        ],
    ],
    [
        releaseType: 'preRelease',
        branchPattern: '^(release|hotfix).*',
        phases: [
//             [
//                 moduleType            : 'pcf',
//                 moduleName            : 'cnp-deploy-pcf',
//                 subCommand            : 'deploy',
//                 branchPattern         : '^(release|hotfix).*',
//                 sdlcEnvironment       : 'prod',
//                 isProductionDeployment: true,
//                 args                  : [
//                     appName                          : 'dg-medical-membership-update-processor-prod-candidate',
//                     foundation                       : 'ps2pcf07',
//                     organization                     : 'Benefit-MGMT-Entities',
//                     space                            : 'Production',
//                     env                              : 'prod',
//                     artifact                         : 'lookup:publishUrl',
//                     autoscale                        : false,
//                     messagingDestinationsTemp : '[TP.DG.MEMBERSHIP.PUBLISHER, TP.MEMBERSHIP.LATEST, TP.MEMBERSHIP.EN.LATEST]',
//                     messagingDestinations : '[TP.DG.MEMBERSHIP.PUBLISHER, TP.MEMBERSHIP.LATEST, TP.MEMBERSHIP.EN.LATEST]',
//                 ]
//             ],
            [
                  moduleType            : 'openshift',
                  moduleName            : 'cnp-deploy-argorollouts',
                  subCommand            : 'deploy',
                  branchPattern         : '^(release|hotfix).*',
                  sdlcEnvironment       : 'prod',
                  isProductionDeployment: true,
                  args                  : [
                      appName                       : 'dg-medical-membership-update-processor-prod',
                      namespace                     : 'membershipentity-prod',
                      platform                      : 'OpenShift',
                      ingressBaseHost               : 'apps-2.hs-2-prod.openshift.evernorthcloud.com',
                      imageName                     : 'lookup:imageName',
                      imageTag                      : 'lookup:tagName',
                      configRepo                    : 'https://github.sys.cigna.com/cigna/membership-prod-argocd',
                      useArgoCD                     : 'true',
                      argoAppName                   : 'dg-medical-membership-update-processor-prod',
                      server                        : 'https://api.hs-2-prod.openshift.evernorthcloud.com:6443',
                      argoCDServer                  : 'argocd-devops.apps.hs-2-prod.openshift.evernorthcloud.com',
                      cluster                       : 'hs-2-prod',
                      configDir                     : 'prod',
                      env                           : 'prod'
                  ]
              ],
//             [
//                 moduleType            : 'pcf',
//                 moduleName            : 'cnp-deploy-pcf',
//                 subCommand            : 'deploy',
//                 branchPattern         : '^(release|hotfix).*',
//                 sdlcEnvironment       : 'dr',
//                 isProductionDeployment: true,
//                 args                  : [
//                     appName                          : 'dg-medical-membership-update-processor-prod-ch3-candidate',
//                     foundation                       : 'ch3pcf03',
//                     organization                     : 'Benefit-MGMT-Entities',
//                     space                            : 'Production',
//                     env                              : 'dr',
//                     artifact                         : 'lookup:publishUrl',
//                     autoscale                        : false,
//                     messagingDestinationsTemp : '[TP.DG.MEMBERSHIP.PUBLISHER, TP.MEMBERSHIP.LATEST, TP.MEMBERSHIP.EN.LATEST]',
//                     messagingDestinations : '[TP.DG.MEMBERSHIP.PUBLISHER, TP.MEMBERSHIP.LATEST, TP.MEMBERSHIP.EN.LATEST]',
//                 ]
//             ]
        ]
    ],
    [
        emailRecipients: '',
        branchPattern: '^(release|hotfix).*',
        lintingTypes: [
            approvalrequest: [
                timeOut: 120,
                message: 'Route Blue ==> Green in prod?',
                id: 'cnpApprove',
                submitter: approvers,
            ],
        ],
    ],
    [
        releaseType: 'release',
        branchPattern: '^(develop|release|hotfix).*',
        phases: [
//             [
//                 moduleType            : 'pcf',
//                 moduleName            : 'cnp-deploy-pcf',
//                 subCommand            : 'cutover',
//                 branchPattern         : '^(release|hotfix).*',
//                 sdlcEnvironment       : 'prod',
//                 isProductionDeployment: true,
//                 args                  : [
//                     appName                          : 'dg-medical-membership-update-processor-prod-candidate',
//                     targetAppName                    : 'dg-medical-membership-update-processor-prod',
//                     foundation                       : 'ps2pcf07',
//                     organization                     : 'Benefit-MGMT-Entities',
//                     space                            : 'Production',
//                     env                              : 'prod'
//                 ]
//             ],
            [
                moduleType            : 'openshift',
                moduleName            : 'cnp-deploy-argorollouts',
                subCommand            : 'promote',
                branchPattern         : '^(release|hotfix).*',
                sdlcEnvironment       : 'prod',
                isProductionDeployment: true,
                args                  : [
                    appName                       : 'dg-medical-membership-update-processor-prod',
                    namespace                     : 'membershipentity-prod',
                    platform                      : 'OpenShift',
                    useArgoCD                     : 'true',
                    server                        : 'https://api.hs-2-prod.openshift.evernorthcloud.com:6443',
                    argoCDServer                  : 'argocd-devops.apps.hs-2-prod.openshift.evernorthcloud.com',
                    cluster                       : 'hs-2-prod',
                    configDir                     : 'prod',
                    env                           : 'prod'
                ]
            ],
//             [
//                 moduleType            : 'pcf',
//                 moduleName            : 'cnp-deploy-pcf',
//                 subCommand            : 'cutover',
//                 branchPattern         : '^(release|hotfix).*',
//                 sdlcEnvironment       : 'dr',
//                 isProductionDeployment: true,
//                 args                  : [
//                     appName                          : 'dg-medical-membership-update-processor-prod-ch3-candidate',
//                     targetAppName                    : 'dg-medical-membership-update-processor-prod-ch3',
//                     foundation                       : 'ch3pcf03',
//                     organization                     : 'Benefit-MGMT-Entities',
//                     space                            : 'Production',
//                     env                              : 'dr'
//                 ]
//             ]
        ]
    ]
]
cignaBuildFlow {
    githubConnectionName = 'github'
    commitStatusName = 'dg-medical-membership-update-processor'
    cloudName = 'dg-medical-update-processor-openshift-devops1'
    phases = phasesToRun
}
}
